suyati-main/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

suyati-main/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "batabase.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

suyati-main/website/auth.py
import email
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from . import predictor
import random
from flask_login import login_user, login_required, logout_user, current_user
import subprocess as sb
import smtplib as s

auth = Blueprint('auth', __name__)

@auth.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        print(first_name)

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/result')
def validate():
    r1=random.randint(0,100)
    datavals,amount,pfr,plg = predictor.run()
    if datavals[r1] == 'fraud':
        email_sender="arjunramesh122@gmail.com"
        email_rec = "arjunramesh122@gmail.com"
        subject='fraud transaction detected ! '
        pswd = 'adrvs0021'
        body='fraud transaction of '+str(amount)+' occured'
        try:
            con = s.SMTP('smtp.gmail.com',587)
            con.starttls()
            con.login(email_sender,pswd)
            msg="Subject:{}\n\n{}".format(subject,body)
            con.sendmail(email_sender,"arjun123@yopmail.com",msg)
            con.quit()
        except:
            print("some error occured")
    return render_template("results.html",amt=amount[r1],value=datavals[r1],perc_f=pfr,perc_l=plg)
    # var_data = sb.check_output("python predictor.py" )
    # var_data = var_data.decode()
    # print(var_data)
    # file = open("predictor.py")
    # var = file.read()
    # exec(var)
    # team_info = zip(amount,datavals)

    # return render_template("results.html",team_info=team_info,perc_f=pfr,perc_l=plg)

suyati-main/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        # if len(note) < 1:
        #     flash('Note is too short!', category='error')
        # else:
        #     new_note = Note(data=note, user_id=current_user.id)
        #     db.session.add(new_note)
        #     db.session.commit()
        #     flash('Note added!', category='success')

    return render_template("home.html", user=current_user)


# @views.route('/delete-note', methods=['POST'])
# def delete_note():
#     note = json.loads(request.data)
#     noteId = note['noteId']
#     note = Note.query.get(noteId)
#     if note:
#         if note.user_id == current_user.id:
#             db.session.delete(note)
#             db.session.commit()

#     return jsonify({})

suyati-main/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css"
    href="instyle.css">

    <title>{% block title %}Home{% endblock %}</title>
    
    <style>
       body
       {
        min-height:100vh;
        background-repeat:no-repeat;
        background-position:center;
        background-size: cover;
        background-attachment:fixed;
        background-image:url({{url_for('static',filename='images/2.jpg')}});
       }
    </style>
  </head>
  
  <body>
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" style="height: 12vh">
          <a class="navbar-brand" href="#">
              <img src="{{url_for('static',filename='images/logo')}}" width="350" height="50" class="d-inline-block align-top" alt="">
          </a>
          <button class="navbar-toggler"
                  type="button"
                  data-toggle="collapse"
                  data-target="#navbar"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbar">
              <div class="navbar-nav">
                  {% if user.is_authenticated %}
                  <a class="nav-item nav-link" id="home" href="/">Home</a>
                  <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                  {% else %}
                  <a class="nav-item nav-link" id="login" href="/">Login</a>
                  <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                  {% endif %}
              </div>
          </div>

      </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

suyati-main/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}
  <h1 align="center"><p style="font-family: MERRIWEATHER; color: #4784e6; margin-bottom: 70px; margin-top: 40px; ">Fraud Detection System</p></h1>
  
<div class="loading container d-flex"  id="loading" style=" width:fit-content; justify-content:center; visibility:collapse;">
   <img height="250" width="250" src="{{url_for('static',filename='images/buffer.gif')}}">
  </div>

  <!-- <div id="change">
    <ul class="list-group list-group-flush" id="notes">
      {% for note in user.notes %}
      <li class="list-group-item">
        {{ note.data }}
        <button type="button" class="close" onClick="deleteNote({{ note.id }})">
          <span aria-hidden="true">&times;</span>
        </button>
      </li>
      {% endfor %}
    </ul> -->

    <div align="center">
      <a  href="{{url_for('auth.validate')}}">
        <button id="click" type="submit" class="btn btn-primary">Start Fraud Verification</button>
      </a>
    </div> 
  </div>
   
  <div id="resultz" style="visibility:collapse; position:absolute; left:45%;">
    <p style="font-size:20px">redirecting please wait...</p>
  </div>
   
   <script>
     var click=document.getElementById("click");
     var loading=document.getElementById("loading");
     var change=document.getElementById("change");
     var resultz=document.getElementById("resultz");

      function reset(){
      loading.style.visibility = "collapse";
    
      resultz.style.visibility = "visible";
    }      
      
      click.onclick=function(){
      
        loading.style.visibility = "visible";
      
        change.style.visibility = "collapse";

        setTimeout(reset,20000);

      }
  
   </script>
    {% endblock %}

suyati-main/website/templates/login.html
{% extends "base.html" %} {% block title %}{% endblock %} {% block content
    %}
    <form method="POST" style="margin-top:80px">
      <h3 align="center"><p style="color:white">LOGIN</p></h3>
      <div class="form-group">
        
        <label for="email"><p style="color:white">Email Address</p></label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password"><p style="color:white">Password</p></label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

suyati-main/website/templates/popup.html
<div class="popup center">
    <div class="icon"></div>
</div> 

<div class="title">
    testing!
</div>
<div class="description">
    this is just a test !
</div>
<div class="dismiss-btn">
    <button id="dismiss-popup-btn">
        dismiss
    </button>
</div>
</div>
<div class="center">
    <button id="open-popup-btn">
        open Popup</button>
</div>

suyati-main/website/templates/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="instyle.css">
      
    <title>Document</title>


    <style>
    body {
      height: 1300px;
      min-height: 100vh;
      background-repeat: no-repeat;
      background-position: center;
      background-size: cover;
      background-attachment: fixed;
    /*  background-image:url( {{url_for('static',filename='images/2.jpg') }} );*/
    }
    </style>
    <style>
        table,
        th,
        td {
            border: 3px solid black;
        }
    </style>
    <style>
        .center {
            margin-left: auto;
            margin-right: auto;
        }

        .child {
            border: 3px solid black;
        }

        .parent {
            display: flex;
        }
    </style>

</head>

<body>




    <nav class="navbar navbar-expand-lg navbar-dark bg-dark " style="height: 10vh">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <!-- <a class="nav-item nav-link" id="home" href="/">Home</a> -->
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            </div>
        </div>
        <a href="#"><img height="53" width="359" src="{{url_for('static',filename='images/logo')}}"></a>
    </nav>

    <h1 class="text-primary" align="center">
        <p style="font-family:verdana; margin-bottom:70px; margin-top:40px;">Recent Transactions</p>
    </h1>
    <div id="loading" style=" width:fit-content; position:absolute; margin-left:30%; visibility:collapse; ">
        <img height="250" width="250" src="{{url_for('static',filename='images/buffer.gif')}}">
    </div>
    <!--
      <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js">
      </script>
      <script type="text/javascript">
          google.charts.load('current',{'packages':['corechart']});
          google.charts.setOnLoadCallback(drawF);
          function drwaF(){
            var perc_l= {{ perc_l|safe }};
            var perc_f= {{ perc_f|safe }};
            var data=google.visualization.arrayToDataTable([

              ["Legit Transaction",perc_l]
              ["Fraud Transaction",perc_f]
            ]);
          var options={title:"aggregate chart",is3D:true};
          var chart=new google.visualization.PieChart(document.getElementById('box'));
          chart.draw(data,options);
          }
      </script>
      <div id="box" style="height:400px;width:500px"></div> -->
    <!-- <table class="center">
        <tr>
          <th>AMOUNT TRANSACTED</th>
          <th>VALIDATION</th>
        </tr>
      <section class="parent">
        <section class="child">
        {% for amt,value in team_info %}
        <tr>
          <td>{{amt}}</td>
          <td>{{value}}</td>
        </tr>
        {% endfor %}
        </section>

      </section>
      </table> -->
    <!-- <table class="center">
      <tr>
        <th>AMOUNT TRANSACTED</th>
        <th>VALIDATION</th>
      </tr>
      <section class="parent">
        <section class="child">
          <tr>
            <td>{{amt}}</td>
            <td>{{value}}</td>
          </tr>
        </section>

      </section>
    </table> -->


    <table class="table container" style="border: 5px solid #007bff ">
        <thead>

        </thead>
        <tbody>
            <tr>
                <th style="border: 5px solid #007bff " scope="col">SL no</th>
                <th style="border: 5px solid #007bff " scope="col">AMOUNT TRANSACTED</th>
                <th style="border: 5px solid #007bff " scope="col">VALIDATION</th>
            </tr>
            <tr>
                <th scope="row">1</th>
                <td style="border: 5px solid #007bff ">{{amt}}</td>
                <td style="border: 5px solid #007bff ">{{value}}</td>
            </tr>

        </tbody>
    </table>

    <div class="d-flex my-5" style="justify-content:center">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Transaction detail
        </button>
    </div>

    <div style="position:relative; left:35%;">
        <div class="piechart"></div>

        <div id="piechart"></div>
    </div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script type="text/javascript">

        // Load google charts
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        // Draw the chart and set the chart values
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['classification', 'count'],
                ['Legit', 28337],
                ['Fraud', 93]
            ]);
            // Optional; add a title and set the width and height of the chart
            var options = { 'title': 'transaction information', 'width': 400, 'height': 400 };
            // Display the chart inside the <div> element with id="piechart"
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }
    </script>


    <div id="change">

        <div align="center">

        </div>
    </div>

    <!-- <a class="btn btn-primary" href="http://localhost:8501/" role="button" style="text-align: center;">Link</a> -->
    <button type="button" class="btn btn-primary btn-lg btn-block"><a href="http://localhost:8501/" style="color:rgb(244, 247, 249)">click here for seeing analysis</a></button>

    <div id="resultz" style="visibility:collapse; position:absolute; left:45%;">
        <p>redirecting please wait...</p>
    </div>

    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Result</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% if value|string() != "legit" %}
                    <div class="alert alert-danger" role="alert">
                        <p>fraudulant transaction detected ,transaction blocked!</p>
                    </div>
                    {% else %}
                    <div class="alert alert-success" role="alert">
                        <p>transaction completed succesfully !</p>
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>



    <script>
        var click = document.getElementById("click");
        var loading = document.getElementById("loading");
        var change = document.getElementById("change");
        var resultz = document.getElementById("resultz");

        function reset() {
            loading.style.visibility = "collapse";

            resultz.style.visibility = "visible";
        }

        click.onclick = function () {

            loading.style.visibility = "visible";

            change.style.visibility = "collapse";

            setTimeout(reset, 5000);

        }

    </script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>

</html>

suyati-main/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Signup{% endblock %} {% block content
    %}
    <form actions="#" method="POST" style="margin-top:80px">
      <h3 align="center"><p style="color:white">SIGN-UP</p></h3>
      <div class="form-group">
        <label for="email"><p style="color:white">Email Address</p></label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password"><p style="color:white">Enter Password</p></label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password"><p style="color:white">Confirm Password</p></label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password2"
          placeholder="Re-Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password"><p style="color:white">First Name</p></label>
        <input
          type="text"
          class="form-control"
          id="password"
          name="firstName"
          placeholder="Enter First Name"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Sign-up</button>
    </form>
    {% endblock %}